### ISSUE TITLE
Mockups

### ISSUE THREAD

**Issue by skateray17** [vkhmara/uprepos#1]
Made without PR.

Registration is not required in TR. You still can implement it, but keep in mind, the main functionality is much more important.
The session is coming... 😄 
No possibility to add a photo.

**Comment by vkhmara** [comment]
What is TR?

**Comment by skateray17** [comment]
Technical requirements

**Comment by vkhmara** [comment]
Ok, I understand you. Thanks!

**Comment by skateray17** [comment]
You are welcome
